avatar
pbstm/api pull request #4
Opened 2021-05-24 15:23 UTC by barabas007

2021-05-24 15:23 UTC, barabas007 commented
avatar

2021-05-24 16:33 UTC, barabas007 commented
rubocop

2021-05-24 16:43 UTC, alxekb requested changes
Please clean up.

2021-05-27 05:36 UTC, alxekb reviewed
Please clean up a little bit more!

2021-05-27 05:36 UTC, alxekb commented on .gitattributes
> +vendor/* linguist-vendored
:eye

2021-05-27 05:36 UTC, alxekb commented on .github/workflows/backend-ci.yml
> +      - name: Install dependencies
🚀

2021-05-27 05:36 UTC, alxekb commented on .gitignore
>  /log/*
😢

2021-05-27 05:36 UTC, alxekb commented on Rakefile
> -end
😭

2021-05-29 17:54 UTC, closed without merging